# Generated by Django 5.1.4 on 2025-01-21 07:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rekamanekg",
            name="waktu",
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
